# Generated by Django 3.0.4 on 2021-12-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20211226_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-list_date']},
        ),
        migrations.AddField(
            model_name='listing',
            name='upvote',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.CharField(auto_created=True, max_length=200, unique=True),
        ),
    ]
